# -------------- services ------------- #
services:
  # ---------------- app ---------------- #
  app:
    container_name: go-url-monitor
    build:
      context: ./volumes/app            # Set the build context to the root where go.mod and go.sum exist
      dockerfile: Dockerfile.dev        # Path to custom Dockerfile
    volumes:
      - ./volumes/app:/app              # Bind mount instead of named volume
      - ./volumes/air_config:/root/.air # Bind mount the Air config
    env_file:
      - ./volumes/app/.env
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1