# Dockerfile for Go project using Air
FROM golang:1.23-alpine

RUN apk update && apk upgrade && \
    apk add --no-cache git openssh tzdata curl

WORKDIR /app

# Set development mode environment variable
ENV DEV_MODE=true

# Install Air globally
RUN go install github.com/air-verse/air@latest

# Start Air for live reloading
CMD ["air"]