# -------------- networks ------------- #
networks:
  default:
    name:       ${STACK_NAME}

# -------------- volumes -------------- #
volumes:
  vol-air_config:
    driver:       local
    driver_opts:
      type:       bind
      o:          bind
      device:     ${ROOT_DIR}/volumes/air_config
  vol-app:
    driver:       local
    driver_opts:
      type:       bind
      o:          bind
      device:     ${ROOT_DIR}/volumes/app

# -------------- services ------------- #
services:
  # ---------------- app ---------------- #
  app:
    container_name: ${STACK_NAME}-app
    image: ${FQDN_REGISTRY}/${STACK_NAME}:dev
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - vol-air_config:/root/.air
      - vol-app:/app
    env_file:
      - stack.env # https://docs.portainer.io/user/docker/stacks/add#environment-variables
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1